export const LOG_USER_REQUEST = 'LOG_USER_REQUEST';
export const LOG_USER_SUCCESS = 'LOG_USER_SUCCESS';
export const LOG_USER_FAILURE = 'LOG_USER_FAILURE';

export const REG_USER_REQUEST = 'REG_USER_REQUEST';
export const REG_USER_SUCCESS = 'REG_USER_SUCCESS';
export const REG_USER_FAILURE = 'REG_USER_FAILURE';

export const LOGOUT_USER_REQUEST = 'LOGOUT_USER_REQUEST';
export const LOGOUT_USER_SUCCESS = 'LOGOUT_USER_SUCCESS';
export const LOGOUT_USER_FAILURE = 'LOGOUT_USER_FAILURE';