export const FETCH_HOLIDAY_REQUEST = 'FETCH_HOLIDAY_REQUEST';
export const FETCH_HOLIDAY_SUCCESS = 'FETCH_HOLIDAY_SUCCESS';
export const FETCH_HOLIDAY_FAILURE = 'FETCH_HOLIDAY_FAILURE';

export const ADD_HOLIDAY_REQUEST = 'ADD_HOLIDAY_REQUEST';
export const ADD_HOLIDAY_SUCCESS = 'ADD_HOLIDAY_SUCCESS';
export const ADD_HOLIDAY_FAILURE = 'ADD_HOLIDAY_FAILURE';

export const DELETE_HOLIDAY_REQUEST = 'DELETE_HOLIDAY_REQUEST';
export const DELETE_HOLIDAY_SUCCESS = 'DELETE_HOLIDAY_SUCCESS';
export const DELETE_HOLIDAY_FAILURE = 'DELETE_HOLIDAY_FAILURE';

export const UPDATE_HOLIDAY_SUCCESS = 'UPDATE_HOLIDAY_SUCCESS';